### ISSUE TITLE
normalizeErrorResponse should do less

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-ajax#175]
Our original intention with `normalizeErrorResponse` was to provide a standard way of presenting error responses. To achieve this goal we detected different scenarios and coerced the errors into JSONAPI format. `normalizeErrorResponse` is now quite unpredictable, especially to new users.

To goal is to reduce the amount of work that `normalizeErrorResponse` does to allow users to opt-in to formatting their error response instead of doing it manually.
# TODO
- [x] Add a deprecation warning to `normalizeErrorResponse` stating that current behavior of `normalizeErrorResponse` is deprecated and will be removed in Ember Ajax 3.0
- [x] Refactor Error Classes to ES6 and add errors getter that throws a deprecation warning that `errors` property will be removed in Ember Ajax 3.0
- [x] Copy the payload onto `payload` property of error instance
# Related Issues
- https://github.com/ember-cli/ember-ajax/issues/157

**Comment by alexlafroscia** [comment]
Is refactoring the `AjaxError` objects going to be a breaking change?  I think the set of `TODOS` needs to land in two PRs; one immediately, and one that gets merged into a `v3.0.0` release branch.  I'm not sure which of those the `AjaxError` changes should land in.

**Comment by taras** [comment]
@alexlafroscia refactoring to ES6 should not be a breaking change but removing errors might be. So, I was thinking that we could do something like this:

```js
export default AjaxError extends Error {
  constructor(payload) {
     this.payload = payload;
  }

  get errors() {
    deprecate('Errors are deprecated and will be removed in 3.0.0');
    return this.payload;
  }
}
```

What do you think?

**Comment by alexlafroscia** [comment]
@taras Yup, I think something like that would be great.

**Comment by jherdman** [comment]
> Is refactoring the AjaxError objects going to be a breaking change?

It looks like the answer is yes. The reason for this is that `err instanceof Ember.Error` is no longer true. I don't think this will be a problem, but it should be raised nonetheless.

**Comment by alexlafroscia** [comment]
Does it have to be the case?  Can we do

```js

class AjaxError extends Ember.Error {

}
```

?

**Comment by jherdman** [comment]
Ah, yes! That worked like a charm. #til

**Comment by jherdman** [comment]
I'm having a helluva time getting the ES6 class refactor to work. As far as I can tell there may be a bug in how Babel is trying to ascertain and call the parent's constructor:

Given:

```javascript
export class AjaxError extends EmberError {
  constructor(errors, message = 'Ajax operation failed') {
    super(message);

    this._errors = errors || [{
      title: 'Ajax Error',
      detail: message
    }];
  }
  // etc
```

We transpile to:

```javascript
  var AjaxError = (function (_EmberError) {
    _inherits(AjaxError, _EmberError);

    function AjaxError(errors) {
      var message = arguments.length <= 1 || arguments[1] === undefined ? 'Ajax operation failed' : arguments[1];

      _classCallCheck(this, AjaxError);

      _get(Object.getPrototypeOf(AjaxError.prototype), 'constructor', this).call(this, message);

      this._errors = errors || [{
        title: 'Ajax Error',
        detail: message
      }];
    }

    // etc...
```

Where `Object.getPrototypeOf(AjaxError.prototype)` evaluates to `Error`, not `Ember.Error`. This breaks tests where we set up detailed messages for unmatched error responses. As far as I can tell the result of calling the prototype's constructor in the former case doesn't produce an instance that's compatible with our existing API (for obvious reasons).

Barring any keen advice the community may have here on fixing this, I'd like to propose that we consider punting on this aspect of the ticket for now.

Additionally I'd like to propose that we make `AjaxError` public. The tests reveal that we do, in fact, return this error when we have an unmatched response. It is therefore a consumable part of our API.

**Comment by taras** [comment]
@jherdman do you have a branch that I could look at?

**Comment by jherdman** [comment]
Yup! Check it out https://github.com/jherdman/ember-ajax/tree/issue-175

**Comment by alexlafroscia** [comment]
> Additionally I'd like to propose that we make AjaxError public. The tests reveal that we do, in fact, return this error when we have an unmatched response. It is therefore a consumable part of our API.

Good idea.

> Barring any keen advice the community may have here on fixing this, I'd like to propose that we consider punting on this aspect of the ticket for now.

Maybe we should make the `*Error` class changes part of the "breaking" part (and release with 3.0.0) and just not have it extend from `Ember.Error`.  Additionally, there are some subtleties to extending from `Error` as it turns out; some info [here](http://stackoverflow.com/a/32749533/2250435).

**Comment by jherdman** [comment]
> Maybe we should make the *Error class changes part of the "breaking" part (and release with 3.0.0) and just not have it extend from Ember.Error

I'm very open to the that. It definitely seems like the path of least resistance.

**Comment by alexlafroscia** [comment]
I saw we just do that then, as long as `AjaxError` extends from `Error`.

**Comment by XaserAcheron** [comment]
Possible discussion point for today's meeting: this seems almost ready to close since @jherdman's refactoring is merged in, but now the only use of `normalizeErrorResponse` in the `v3.0.0` branch (outside of tests) is to generate the now-deprecated `errors` property. Should we also deprecate the `normalizeErrorResponse` function itself?

[Welp, I'm using "we" already.]

**Comment by taras** [comment]
I think we were planning to deprecate the built-in behaviour of `normalizeErrorResponse` and make it opt-in. We can keep the hook for people to add their own `normalizeErrorResponse` behaviour.

You're welcome to "we" 👍 .

**Comment by taras** [comment]
@jherdman when you get a chance, can you please comment via text what you were going to say on the call?

**Comment by XaserAcheron** [comment]
Yeah, the call went "poof" on us, I'm afraid.

I think my thoughts from earlier were a bit half-formed (and probably not that useful anyhow). I'll noodle it a bit more and see if things clear up. Unless that happens, carry on. ;P

Thinking on @alexlafroscia's point brought up during the call, it would indeed be a bit disruptive to add a deprecation to 2.0 telling folks to opt-in or opt-out; though I'm generally a fan of advance warnings, I'm kinda on the fence about it. More noodling to be had.

**Comment by alexlafroscia** [comment]
Closed by #265
