### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-ajax#37]
Ember Ajax was created to provide an up to date alternative to `ic-ajax` and to unify how Ember applications make XHR requests. A few weeks later, @tomdale wrote a thoughtful RFC titled [Network Service](https://github.com/emberjs/rfcs/pull/94), where he outlined a similar need from FastBoot prospective. 

In Tom's [follow up](https://gist.github.com/tomdale/203ea125acd0be8b5f1f) to the RFC, he notes that *One of the explicit goals of Ember.js is to provide developers with the ability to use future features of the web platform today.* It is our goal to make Ember Ajax use [fetch API](https://github.com/github/fetch) by default and do so without breaking apps that use `ember-ajax`. We'll do this in the Emberway™ - it will be transparent for most or require some refactoring for others.

From the start, the goal of this project was to unify the mechanism that Ember Data uses to make Ajax requests with that which we use to make ad-hoc requests in our applications. We already started a conversation with the Ember Data Core team to find a path to move forward on integrating Ember Ajax with Ember Data. 

There are several issues that remain unresolved that were inherited from Ember Data code. The primarily revolve around the need to expose information about failed requests #22.

## TODO

- [x] Remove `ic-ajax` related code - #35
- [x] Refactor Ember Ajax into an ES6 and consume it in Ajax Service - #31 
- [x] Add missing Error types - #36
- [x] Add error detail handling from Ember Data #43 

/cc @tomdale @stefanpenner @alexlafroscia

**Comment by alexlafroscia** [comment]
:+1: I'll get cracking on this list this week!

**Comment by taras** [comment]
Nice!

**Comment by alexlafroscia** [comment]
So, I'm starting to work on a PR to address this:

> Refactor Ember Ajax into an ES6 and consume it in Ajax Service

and just wanted to verify that my thoughts so far are correct.  The idea is that we want to pull out each of the methods in the service into their own, separate functions that can be imported as ES6 modules.  This way, someone could import the request functionality without using the whole service.  Then, the service gets modified to rely on these functions, while maintaining people's ability to overwrite methods of the service to change functionality where they need to.  Is that correct?

**Comment by alexlafroscia** [comment]
> 4/4
:tada:

**Comment by taras** [comment]
@alexlafroscia thank you for the great work on this!

**Comment by alexlafroscia** [comment]
Happy to help :smile: do you want to do a beta release before tagging 2.0? If so, would it just be to see if anyone encounters bugs, or is there other things to clean up before release? I'm curious if there's enough people using this at this point for us to get good bug reports or feedback.

**Comment by jamesdixon** [comment]
@alexlafroscia I'll upgrade to the beta and let you guys know if I find anything. Nice work!

**Comment by stefanpenner** [comment]
:+1:

**Comment by alexlafroscia** [comment]
Thanks @jamesdixon! That's really helpful

**Comment by rwjblue** [comment]
Seems like all the checklist items are done, and the last beta was released a few weeks ago. Anything holding this back from final 2.0.0?

**Comment by alexlafroscia** [comment]
@rwjblue sorry, that's my fault :frown: school has been really busy for me, as this is my last semester.  @taras and I have been planning to cut the `2.0` release yesterday or today, I just wanted to get his approval before doing so.  If you think it's good, then I'll get that done today.

**Comment by taras** [comment]
@alexlafroscia we're good to go, so let's do it!

**Comment by webark** [comment]
woop woop!!! Great job yoi all! :tada:

**Comment by alexlafroscia** [comment]
Published! :thumbsup:

**Comment by taras** [comment]
Congratulations! Great Job!

**Comment by rwjblue** [comment]
Updating ember-cli in https://github.com/ember-cli/ember-cli/pull/5769
